name: Build marketplace images
description: |
  Building disk images for
    1. DigitalOcean
    2. AWS (AMI)
    .. and more

inputs:
  tag:
    description: |
      Rocket.Chat version tag
    required: true
  digitalocean-token:
    required: false
    description: DigitalOcean token
  aws-key-id:
    required: false
    description: AWS key id
  aws-secret-key:
    required: false
    description: AWS secret key
  source:
    description: Packer source
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: RocketChat/rocketchat-packer

    - name: Validate template
      uses: hashicorp/packer-github-actions@master
      with:
        command: validate
        arguments: -syntax-only
        target: rocketchat.pkr.hcl

    - name: Initialize plugins
      uses: hashicorp/packer-github-actions@master
      with:
        command: init
        target: rocketchat.pkr.hcl

    - name: Build images
      uses: hashicorp/packer-github-actions@master
      with:
        command: build
        arguments: "-color=false -on-error=abort -only=source.${{ inputs.source }}"
        target: rocketchat.pkr.hcl
      env:
        PACKER_LOG: '1'
        PKR_VAR_rocketchat_version: ${{ inputs.tag }}
        PKR_VAR_do_token: ${{ inputs.digitalocean-token }}
        PKR_VAR_aws_key_id: ${{ inputs.aws-key-id }}
        PKR_VAR_aws_secret_key: ${{ inputs.aws-secret-key }}

