name: Build Marketplace Images

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  ManualBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Check latest
        if: ${{ github.event_name == 'workflow_dispatch' }}
        id: preflight
        run: |
          command -v jq &>/dev/null || sudo apt install jq -y
          latest_stable="$(curl -s https://releases.rocket.chat/stable/info | jq -r .tag)"
          latest_tag_here="$(
            git -c 'versionsort.suffix=-' ls-remote -t --exit-code --refs --sort=-v:refname "https://github.com/RocketChat/rocketchat-packer" '*' |
            awk -F/ '$NF !~ /rc|beta/ { print $NF; exit }'
          )"
          echo "latest_stable: $latest_stable"
          echo "latest_tag_here: $latest_tag_here"
          if [[ "$latest_tag_here" != "$latest_stable" ]]; then
            echo "run=true" >>$GITHUB_OUTPUT
            echo "tag=$latest_stable" >>$GITHUB_OUTPUT
          else
            echo "run=false" >>$GITHUB_OUTPUT
          fi

      - name: Build image
        if: ${{ steps.preflight.outputs.run == 'true' }}
        uses: RocketChat/rocketchat-packer@main
        with:
          github-token: ${{ secrets.GH_TOKEN_PERSONAL }}
          aws-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-key: ${{ secrets.AWS_SECRET_KEY }}
          digitalocean-token: ${{ secrets.DO_TOKEN }}
          tag: ${{ steps.preflight.outputs.tag }}

  TriggeredBuild:
    if: ${{ github.event_name == 'repository_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Build image
        uses: RocketChat/rocketchat-packer@main
        with:
          github-token: ${{ secrets.GH_TOKEN_PERSONAL }}
          aws-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-key: ${{ secrets.AWS_SECRET_KEY }}
          digitalocean-token: ${{ secrets.DO_TOKEN }}
          tag: ${{ github.event.client_payload.tag }}
